const Candidates = [
    {  id:'1',
      Candidate_name: 'John Smith',
      Photo: 'https://via.placeholder.com/150',
      Location: 'New York',
      Date_Applied: '2022-01-01',
      Stage: 'Source'
    },
    {  id:'2',
      Candidate_name: 'Jane Doe',
      Photo: 'https://via.placeholder.com/150',
      Location: 'San Francisco',
      Date_Applied: '2022-02-01',
      Stage: 'Source'
    },
    {  id:'3',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Applied'
      },
      {  id:'4',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Applied'
      },
      {  id:'5',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'In-Touch'
      },
      {  id:'6',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'In-Touch'
      },
      {  id:'7',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Interview'
      },
      {  id:'8',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Interview'
      },
      {  id:'9',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Hired'
      },
      {  id:'10',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Hired'
      },
      {  id:'11',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Rejected'
      },
      {  id:'12',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Rejected'
      },
      {  id:'13',
        Candidate_name: 'Jane Doe',
        Photo: 'https://via.placeholder.com/150',
        Location: 'San Francisco',
        Date_Applied: '2022-02-01',
        Stage: 'Rejected'
      },
    // Add more candidates as needed
  ];

export default Candidates; 